[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200
evm-version = "cancun"
via_ir = true

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 1, url = "https://api.etherscan.io/v2/api?chainid=1" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api.etherscan.io/v2/api?chainid=11155111" }
polygon = { key = "${ETHERSCAN_API_KEY}", chain = 137, url = "https://api.etherscan.io/v2/api?chainid=137" }
polygon_amoy = { key = "${ETHERSCAN_API_KEY}", chain = 80002, url = "https://api.etherscan.io/v2/api?chainid=80002" }
unichain = { key = "${ETHERSCAN_API_KEY}", chain = 130, url = "https://api.etherscan.io/v2/api?chainid=130" }
unichain_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 1301, url = "https://api.etherscan.io/v2/api?chainid=1301" }

[fmt]
#line_length = 150

[fuzz]
runs = 10_000

[invariant]
runs = 2048
depth = 100
fail_on_revert = false

[lint]
enabled = false
